export const CAR_CLASSES = [
  { value: 'ARC_Cam', label: 'ARC Camaro'},
  { value: 'Procar', label: 'BMW M1 ProCar'},
  { value: 'Cat620R', label: 'Catherham 620R'},
  { value: 'Cat_Academy', label: 'Catherham Academy'},
  { value: 'Cat_Superlight', label: 'Catherham Superlight'},
  { value: 'Cat_Supersport', label: 'Catherham Supersport'},
  { value: 'CopaClassicB', label: 'Copa Classics B'},
  { value: 'CopaClassicFL', label: 'Copa Classics FL'},
  { value: 'CopaFusca', label: 'Copa Fusca'},
  { value: 'CopaTruck', label: 'Copa Truck'},
  { value: 'CopaUno', label: 'Copa Uno'},
  { value: 'Hot Cars', label: 'Hot Cars'},
  { value: 'DPI', label: 'DPI [Racin\' USA pt.1 DLC]'},
  { value: 'F-3', label: 'Formula 3'},
  { value: 'F-Classic_Gen1', label: 'Formula Classic Gen.1 (1986)'},
  { value: 'F-Classic_Gen2', label: 'Formula Classic Gen.2 (1988)'},
  { value: 'F-Classic_Gen3', label: 'Formula Classic Gen.3 (1991)'},
  { value: 'F-Reiza', label: 'Formula Reiza (2011)'},
  { value: 'F-Retro_Gen1', label: 'Formula Retro Gen.1 (1973 - 1974)'},
  { value: 'F-Retro_Gen2', label: 'Formula Retro Gen.2 (1977)'},
  { value: 'F-Retro_Gen3', label: 'Formula Retro Gen.2 (1983)'},
  { value: 'F-Trainer', label: 'Formula Trainer'},
  { value: 'F-Trainer_A', label: 'Formula Trainer Advanced'},
  { value: 'F-Ultimate', label: 'Formula Ultimate (2018)'},
  { value: 'F-Ultimate_Gen2', label: 'Formula Ultimate Gen.2 (2022)'},
  { value: 'F-USA_Gen1', label: 'Formula USA Gen.1 (1995) [Racin\' USA pt.2 DLC]'},
  { value: 'F-USA_Gen2', label: 'Formula USA Gen.2 (1998) [Racin\' USA pt.2 DLC]'},
  { value: 'F-USA_Gen3', label: 'Formula USA Gen.3 (2000) [Racin\' USA pt.2 DLC]'},
  { value: 'F-V10_Gen1', label: 'Formula V10 Gen.1 (1998)'},
  { value: 'F-V10_Gen2', label: 'Formula V10 Gen.1 (2002)'},
  { value: 'F-V12', label: 'Formula V10 Gen.1 (1994)'},
  { value: 'F-Vee', label: 'Formula Vee'},
  { value: 'F-Vintage_Gen1', label: 'Formula Vintage Gen.1 (1967)'},
  { value: 'F-Vintage_Gen2', label: 'Formula Vintage Gen.1 (1969)'},
  { value: 'P1', label: 'P1'},
  { value: 'P2', label: 'P2'},
  { value: 'P3', label: 'P3'},
  { value: 'P4', label: 'P4'},
  { value: 'G40Cup', label: 'Ginetta G40 Cup'},
  { value: 'G55Supercup', label: 'Ginetta G55 SuperCup'},
  { value: 'GT1', label: 'GT1'},
  { value: 'GT3', label: 'GT3'},
  { value: 'GT4', label: 'GT4'},
  { value: 'GT5', label: 'GT5'},
  { value: 'GTE', label: 'GTE [Racin\' USA pt.1 DLC]'},
  { value: 'GTOpen', label: 'Ultimas GTR'},
  { value: 'Group A', label: 'Group A Touring Car'},
  { value: 'Carrera Cup', label: 'Porsche Carrera Cup'},
  { value: 'KartRental', label: 'Kart Rental'},
  { value: 'KartShifter', label: 'Kart Shifter'},
  { value: 'Kart125cc', label: 'Karts 125CC'},
  { value: 'KartGX390', label: 'Kart GX390'},
  { value: 'SuperKart', label: 'Super Karts'},
  { value: 'LancerCup', label: 'Mistubishi Lancer Cup'},
  { value: 'MiniChallenge', label: 'Mini Cup JCW'},
  { value: 'Montana', label: 'Copa Montana'},
  { value: 'OldStock', label: 'Old Stocks'},
  { value: 'Opala79', label: 'Stock Car Opala 1979'},
  { value: 'Opala86', label: 'Stock Car Opala 1986'},
  { value: 'StockCar99', label: 'Stock Car Omega 1999'},
  { value: 'StockCarV8', label: 'Stock Car Brasil 2019'},
  { value: 'StockCarV8_2020', label: 'Stock Car Brasil 2020'},
  { value: 'StockCarV8_2021', label: 'Stock Car Brasil 2021'},
  { value: 'StockCarV8_2022', label: 'Stock Car Brasil 2022'},
  { value: 'SprintRace', label: 'Sprint Race 2019'},
  { value: 'Street', label: 'Street Cars'},
  { value: 'SuperV8', label: 'Australian Super V8\'s'},
  { value: 'TC60S', label: 'Vintage Tourings 60\'s'},
  { value: 'TC60S2', label: 'Vintage Tourings 60\'s  - 2'},
  { value: 'TC70S', label: 'Vintage Tourings 70\'s'},
  { value: 'TSICup', label: 'VW TSI Cup'},
];
