import { CarCategory, CarClass } from "../models/cars";

export const CAR_CLASSES: CarClass[] = [
  { value: 'ARC_Cam', label: 'ARC Camaro', category: 'touring'},
  { value: 'Procar', label: 'BMW M1 ProCar', category: 'touring'},
  { value: 'Group A', label: 'Group A Touring Car', category: 'touring'},
  { value: 'Cat620R', label: 'Catherham 620R', category: 'caterhams'},
  { value: 'Cat_Academy', label: 'Catherham Academy', category: 'caterhams'},
  { value: 'Cat_Superlight', label: 'Catherham Superlight', category: 'caterhams'},
  { value: 'Cat_Supersport', label: 'Catherham Supersport', category: 'caterhams'},
  { value: 'CopaClassicB', label: 'Copa Classics B', category: 'touring'},
  { value: 'CopaClassicFL', label: 'Copa Classics FL', category: 'touring'},
  { value: 'CopaFusca', label: 'Copa Fusca', category: 'touring'},
  { value: 'CopaTruck', label: 'Copa Truck', category: 'touring'},
  { value: 'CopaUno', label: 'Copa Uno', category: 'touring'},
  { value: 'Hot Cars', label: 'Hot Cars', category: 'touring'},
  { value: 'F-3', label: 'Formula 3', category: 'formula'},
  { value: 'F-Classic_Gen1', label: 'Formula Classic Gen.1 (1986)', category: 'formula'},
  { value: 'F-Classic_Gen2', label: 'Formula Classic Gen.2 (1988)', category: 'formula'},
  { value: 'F-Classic_Gen3', label: 'Formula Classic Gen.3 (1991)', category: 'formula'},
  { value: 'F-Reiza', label: 'Formula Reiza (2011)', category: 'formula'},
  { value: 'F-Retro_Gen1', label: 'Formula Retro Gen.1 (1973 - 1974)', category: 'formula'},
  { value: 'F-Retro_Gen2', label: 'Formula Retro Gen.2 (1977)', category: 'formula'},
  { value: 'F-Retro_Gen3', label: 'Formula Retro Gen.2 (1983)', category: 'formula'},
  { value: 'F-Trainer', label: 'Formula Trainer', category: 'formula'},
  { value: 'F-Trainer_A', label: 'Formula Trainer Advanced', category: 'formula'},
  { value: 'F-Ultimate', label: 'Formula Ultimate (2018)', category: 'formula'},
  { value: 'F-Ultimate_Gen2', label: 'Formula Ultimate Gen.2 (2022)', category: 'formula'},
  { value: 'F-USA_Gen1', label: 'Formula USA Gen.1 (1995) [Racin\' USA pt.2 DLC]', category: 'formula'},
  { value: 'F-USA_Gen2', label: 'Formula USA Gen.2 (1998) [Racin\' USA pt.2 DLC]', category: 'formula'},
  { value: 'F-USA_Gen3', label: 'Formula USA Gen.3 (2000) [Racin\' USA pt.2 DLC]', category: 'formula'},
  { value: 'F-V10_Gen1', label: 'Formula V10 Gen.1 (1998)', category: 'formula'},
  { value: 'F-V10_Gen2', label: 'Formula V10 Gen.1 (2002)', category: 'formula'},
  { value: 'F-V12', label: 'Formula V10 Gen.1 (1994)', category: 'formula'},
  { value: 'F-Vee', label: 'Formula Vee', category: 'formula'},
  { value: 'F-Vintage_Gen1', label: 'Formula Vintage Gen.1 (1967)', category: 'formula'},
  { value: 'F-Vintage_Gen2', label: 'Formula Vintage Gen.1 (1969)', category: 'formula'},
  { value: 'DPI', label: 'DPI [Racin\' USA pt.1 DLC]', category: 'endurace'},
  { value: 'P1', label: 'P1', category: 'endurace'},
  { value: 'P2', label: 'P2', category: 'endurace'},
  { value: 'P3', label: 'P3', category: 'endurace'},
  { value: 'P4', label: 'P4', category: 'endurace'},
  { value: 'Group C', label: 'Group C Prototypes', category: 'endurace'},
  { value: 'G40Cup', label: 'Ginetta G40 Cup', category: 'gt'},
  { value: 'G55Supercup', label: 'Ginetta G55 SuperCup', category: 'gt'},
  { value: 'GT1', label: 'GT1', category: 'gt'},
  { value: 'GT3', label: 'GT3', category: 'gt'},
  { value: 'GT4', label: 'GT4', category: 'gt'},
  { value: 'GT5', label: 'GT5', category: 'gt'},
  { value: 'GTE', label: 'GTE [Racin\' USA pt.1 DLC]', category: 'gt'},
  { value: 'GTOpen', label: 'Ultimas GTR', category: 'gt'},
  { value: 'Carrera Cup', label: 'Porsche Carrera Cup', category: 'gt'},
  { value: 'KartRental', label: 'Kart Rental', category: 'karts'},
  { value: 'KartShifter', label: 'Kart Shifter', category: 'karts'},
  { value: 'Kart125cc', label: 'Karts 125CC', category: 'karts'},
  { value: 'KartGX390', label: 'Kart GX390', category: 'karts'},
  { value: 'SuperKart', label: 'Super Karts', category: 'karts'},
  { value: 'LancerCup', label: 'Mistubishi Lancer Cup', category: 'touring'},
  { value: 'MiniChallenge', label: 'Mini Cup JCW', category: 'touring'},
  { value: 'Montana', label: 'Copa Montana', category: 'touring'},
  { value: 'OldStock', label: 'Old Stocks', category: 'stock_cars'},
  { value: 'Opala79', label: 'Stock Car Opala 1979', category: 'stock_cars'},
  { value: 'Opala86', label: 'Stock Car Opala 1986', category: 'stock_cars'},
  { value: 'StockCar99', label: 'Stock Car Omega 1999', category: 'stock_cars'},
  { value: 'StockCarV8', label: 'Stock Car Brasil 2019', category: 'stock_cars'},
  { value: 'StockCarV8_2020', label: 'Stock Car Brasil 2020', category: 'stock_cars'},
  { value: 'StockCarV8_2021', label: 'Stock Car Brasil 2021', category: 'stock_cars'},
  { value: 'StockCarV8_2022', label: 'Stock Car Brasil 2022', category: 'stock_cars'},
  { value: 'SprintRace', label: 'Sprint Race 2019', category: 'touring'},
  { value: 'SuperV8', label: 'Australian Super V8\'s', category: 'touring'},
  { value: 'TC60S', label: 'Vintage Tourings 60\'s', category: 'touring'},
  { value: 'TC60S2', label: 'Vintage Tourings 60\'s  - 2', category: 'touring'},
  { value: 'TC70S', label: 'Vintage Tourings 70\'s', category: 'touring'},
  { value: 'Street', label: 'Street Cars', category: 'street'},
  { value: 'TSICup', label: 'VW TSI Cup', category: 'street'},
];

export const CAR_CATEGORIES: CarCategory[] = [
  { value: 'stock_cars', label: 'Stock Cars'},
  { value: 'touring', label: 'Touring Cars'},
  { value: 'endurace', label: 'Endurace'},
  { value: 'gt', label: 'GTs'},
  { value: 'formula', label: 'Formula'},
  { value: 'caterhams', label: 'Caterhams'},
  { value: 'karts', label: 'Karts'},
  { value: 'street', label: 'Street Cars'},
];
