export const COUNTRY_CODES = [
  {
     name:"Afghanistan",
     alphaCode:"AFG",
     countryCode:"004"
  },
  {
     name:"Åland Islands",
     alphaCode:"ALA",
     countryCode:"248"
  },
  {
     name:"Albania",
     alphaCode:"ALB",
     countryCode:"008"
  },
  {
     name:"Algeria",
     alphaCode:"DZA",
     countryCode:"012"
  },
  {
     name:"American Samoa",
     alphaCode:"ASM",
     countryCode:"016"
  },
  {
     name:"Andorra",
     alphaCode:"AND",
     countryCode:"020"
  },
  {
     name:"Angola",
     alphaCode:"AGO",
     countryCode:"024"
  },
  {
     name:"Anguilla",
     alphaCode:"AIA",
     countryCode:"660"
  },
  {
     name:"Antarctica",
     alphaCode:"ATA",
     countryCode:"010"
  },
  {
     name:"Antigua and Barbuda",
     alphaCode:"ATG",
     countryCode:"028"
  },
  {
     name:"Argentina",
     alphaCode:"ARG",
     countryCode:"032"
  },
  {
     name:"Armenia",
     alphaCode:"ARM",
     countryCode:"051"
  },
  {
     name:"Aruba",
     alphaCode:"ABW",
     countryCode:"533"
  },
  {
     name:"Australia",
     alphaCode:"AUS",
     countryCode:"036"
  },
  {
     name:"Austria",
     alphaCode:"AUT",
     countryCode:"040"
  },
  {
     name:"Azerbaijan",
     alphaCode:"AZE",
     countryCode:"031"
  },
  {
     name:"Bahamas",
     alphaCode:"BHS",
     countryCode:"044"
  },
  {
     name:"Bahrain",
     alphaCode:"BHR",
     countryCode:"048"
  },
  {
     name:"Bangladesh",
     alphaCode:"BGD",
     countryCode:"050"
  },
  {
     name:"Barbados",
     alphaCode:"BRB",
     countryCode:"052"
  },
  {
     name:"Belarus",
     alphaCode:"BLR",
     countryCode:"112"
  },
  {
     name:"Belgium",
     alphaCode:"BEL",
     countryCode:"056"
  },
  {
     name:"Belize",
     alphaCode:"BLZ",
     countryCode:"084"
  },
  {
     name:"Benin",
     alphaCode:"BEN",
     countryCode:"204"
  },
  {
     name:"Bermuda",
     alphaCode:"BMU",
     countryCode:"060"
  },
  {
     name:"Bhutan",
     alphaCode:"BTN",
     countryCode:"064"
  },
  {
     name:"Bolivia (Plurinational State of)",
     alphaCode:"BOL",
     countryCode:"068"
  },
  {
     name:"Bonaire, Sint Eustatius and Saba",
     alphaCode:"BES",
     countryCode:"535"
  },
  {
     name:"Bosnia and Herzegovina",
     alphaCode:"BIH",
     countryCode:"070"
  },
  {
     name:"Botswana",
     alphaCode:"BWA",
     countryCode:"072"
  },
  {
     name:"Bouvet Island",
     alphaCode:"BVT",
     countryCode:"074"
  },
  {
     name:"Brazil",
     alphaCode:"BRA",
     countryCode:"076"
  },
  {
     name:"British Indian Ocean Territory",
     alphaCode:"IOT",
     countryCode:"086"
  },
  {
     name:"Brunei Darussalam",
     alphaCode:"BRN",
     countryCode:"096"
  },
  {
     name:"Bulgaria",
     alphaCode:"BGR",
     countryCode:"100"
  },
  {
     name:"Burkina Faso",
     alphaCode:"BFA",
     countryCode:"854"
  },
  {
     name:"Burundi",
     alphaCode:"BDI",
     countryCode:"108"
  },
  {
     name:"Cabo Verde",
     alphaCode:"CPV",
     countryCode:"132"
  },
  {
     name:"Cambodia",
     alphaCode:"KHM",
     countryCode:"116"
  },
  {
     name:"Cameroon",
     alphaCode:"CMR",
     countryCode:"120"
  },
  {
     name:"Canada",
     alphaCode:"CAN",
     countryCode:"124"
  },
  {
     name:"Cayman Islands",
     alphaCode:"CYM",
     countryCode:"136"
  },
  {
     name:"Central African Republic",
     alphaCode:"CAF",
     countryCode:"140"
  },
  {
     name:"Chad",
     alphaCode:"TCD",
     countryCode:"148"
  },
  {
     name:"Chile",
     alphaCode:"CHL",
     countryCode:"152"
  },
  {
     name:"China",
     alphaCode:"CHN",
     countryCode:"156"
  },
  {
     name:"Christmas Island",
     alphaCode:"CXR",
     countryCode:"162"
  },
  {
     name:"Cocos (Keeling) Islands",
     alphaCode:"CCK",
     countryCode:"166"
  },
  {
     name:"Colombia",
     alphaCode:"COL",
     countryCode:"170"
  },
  {
     name:"Comoros",
     alphaCode:"COM",
     countryCode:"174"
  },
  {
     name:"Congo",
     alphaCode:"COG",
     countryCode:"178"
  },
  {
     name:"Congo, Democratic Republic of the",
     alphaCode:"COD",
     countryCode:"180"
  },
  {
     name:"Cook Islands",
     alphaCode:"COK",
     countryCode:"184"
  },
  {
     name:"Costa Rica",
     alphaCode:"CRI",
     countryCode:"188"
  },
  {
     name:"Côte d'Ivoire",
     alphaCode:"CIV",
     countryCode:"384"
  },
  {
     name:"Croatia",
     alphaCode:"HRV",
     countryCode:"191"
  },
  {
     name:"Cuba",
     alphaCode:"CUB",
     countryCode:"192"
  },
  {
     name:"Curaçao",
     alphaCode:"CUW",
     countryCode:"531"
  },
  {
     name:"Cyprus",
     alphaCode:"CYP",
     countryCode:"196"
  },
  {
     name:"Czechia",
     alphaCode:"CZE",
     countryCode:"203"
  },
  {
     name:"Denmark",
     alphaCode:"DNK",
     countryCode:"208"
  },
  {
     name:"Djibouti",
     alphaCode:"DJI",
     countryCode:"262"
  },
  {
     name:"Dominica",
     alphaCode:"DMA",
     countryCode:"212"
  },
  {
     name:"Dominican Republic",
     alphaCode:"DOM",
     countryCode:"214"
  },
  {
     name:"Ecuador",
     alphaCode:"ECU",
     countryCode:"218"
  },
  {
     name:"Egypt",
     alphaCode:"EGY",
     countryCode:"818"
  },
  {
     name:"El Salvador",
     alphaCode:"SLV",
     countryCode:"222"
  },
  {
     name:"Equatorial Guinea",
     alphaCode:"GNQ",
     countryCode:"226"
  },
  {
     name:"Eritrea",
     alphaCode:"ERI",
     countryCode:"232"
  },
  {
     name:"Estonia",
     alphaCode:"EST",
     countryCode:"233"
  },
  {
     name:"Eswatini",
     alphaCode:"SWZ",
     countryCode:"748"
  },
  {
     name:"Ethiopia",
     alphaCode:"ETH",
     countryCode:"231"
  },
  {
     name:"Falkland Islands (Malvinas)",
     alphaCode:"FLK",
     countryCode:"238"
  },
  {
     name:"Faroe Islands",
     alphaCode:"FRO",
     countryCode:"234"
  },
  {
     name:"Fiji",
     alphaCode:"FJI",
     countryCode:"242"
  },
  {
     name:"Finland",
     alphaCode:"FIN",
     countryCode:"246"
  },
  {
     name:"France",
     alphaCode:"FRA",
     countryCode:"250"
  },
  {
     name:"French Guiana",
     alphaCode:"GUF",
     countryCode:"254"
  },
  {
     name:"French Polynesia",
     alphaCode:"PYF",
     countryCode:"258"
  },
  {
     name:"French Southern Territories",
     alphaCode:"ATF",
     countryCode:"260"
  },
  {
     name:"Gabon",
     alphaCode:"GAB",
     countryCode:"266"
  },
  {
     name:"Gambia",
     alphaCode:"GMB",
     countryCode:"270"
  },
  {
     name:"Georgia",
     alphaCode:"GEO",
     countryCode:"268"
  },
  {
     name:"Germany",
     alphaCode:"DEU",
     countryCode:"276"
  },
  {
     name:"Ghana",
     alphaCode:"GHA",
     countryCode:"288"
  },
  {
     name:"Gibraltar",
     alphaCode:"GIB",
     countryCode:"292"
  },
  {
     name:"Greece",
     alphaCode:"GRC",
     countryCode:"300"
  },
  {
     name:"Greenland",
     alphaCode:"GRL",
     countryCode:"304"
  },
  {
     name:"Grenada",
     alphaCode:"GRD",
     countryCode:"308"
  },
  {
     name:"Guadeloupe",
     alphaCode:"GLP",
     countryCode:"312"
  },
  {
     name:"Guam",
     alphaCode:"GUM",
     countryCode:"316"
  },
  {
     name:"Guatemala",
     alphaCode:"GTM",
     countryCode:"320"
  },
  {
     name:"Guernsey",
     alphaCode:"GGY",
     countryCode:"831"
  },
  {
     name:"Guinea",
     alphaCode:"GIN",
     countryCode:"324"
  },
  {
     name:"Guinea-Bissau",
     alphaCode:"GNB",
     countryCode:"624"
  },
  {
     name:"Guyana",
     alphaCode:"GUY",
     countryCode:"328"
  },
  {
     name:"Haiti",
     alphaCode:"HTI",
     countryCode:"332"
  },
  {
     name:"Heard Island and McDonald Islands",
     alphaCode:"HMD",
     countryCode:"334"
  },
  {
     name:"Holy See",
     alphaCode:"VAT",
     countryCode:"336"
  },
  {
     name:"Honduras",
     alphaCode:"HND",
     countryCode:"340"
  },
  {
     name:"Hong Kong",
     alphaCode:"HKG",
     countryCode:"344"
  },
  {
     name:"Hungary",
     alphaCode:"HUN",
     countryCode:"348"
  },
  {
     name:"Iceland",
     alphaCode:"ISL",
     countryCode:"352"
  },
  {
     name:"India",
     alphaCode:"IND",
     countryCode:"356"
  },
  {
     name:"Indonesia",
     alphaCode:"IDN",
     countryCode:"360"
  },
  {
     name:"Iran (Islamic Republic of)",
     alphaCode:"IRN",
     countryCode:"364"
  },
  {
     name:"Iraq",
     alphaCode:"IRQ",
     countryCode:"368"
  },
  {
     name:"Ireland",
     alphaCode:"IRL",
     countryCode:"372"
  },
  {
     name:"Isle of Man",
     alphaCode:"IMN",
     countryCode:"833"
  },
  {
     name:"Israel",
     alphaCode:"ISR",
     countryCode:"376"
  },
  {
     name:"Italy",
     alphaCode:"ITA",
     countryCode:"380"
  },
  {
     name:"Jamaica",
     alphaCode:"JAM",
     countryCode:"388"
  },
  {
     name:"Japan",
     alphaCode:"JPN",
     countryCode:"392"
  },
  {
     name:"Jersey",
     alphaCode:"JEY",
     countryCode:"832"
  },
  {
     name:"Jordan",
     alphaCode:"JOR",
     countryCode:"400"
  },
  {
     name:"Kazakhstan",
     alphaCode:"KAZ",
     countryCode:"398"
  },
  {
     name:"Kenya",
     alphaCode:"KEN",
     countryCode:"404"
  },
  {
     name:"Kiribati",
     alphaCode:"KIR",
     countryCode:"296"
  },
  {
     name:"Korea (Democratic People's Republic of)",
     alphaCode:"PRK",
     countryCode:"408"
  },
  {
     name:"Korea, Republic of",
     alphaCode:"KOR",
     countryCode:"410"
  },
  {
     name:"Kuwait",
     alphaCode:"KWT",
     countryCode:"414"
  },
  {
     name:"Kyrgyzstan",
     alphaCode:"KGZ",
     countryCode:"417"
  },
  {
     name:"Lao People's Democratic Republic",
     alphaCode:"LAO",
     countryCode:"418"
  },
  {
     name:"Latvia",
     alphaCode:"LVA",
     countryCode:"428"
  },
  {
     name:"Lebanon",
     alphaCode:"LBN",
     countryCode:"422"
  },
  {
     name:"Lesotho",
     alphaCode:"LSO",
     countryCode:"426"
  },
  {
     name:"Liberia",
     alphaCode:"LBR",
     countryCode:"430"
  },
  {
     name:"Libya",
     alphaCode:"LBY",
     countryCode:"434"
  },
  {
     name:"Liechtenstein",
     alphaCode:"LIE",
     countryCode:"438"
  },
  {
     name:"Lithuania",
     alphaCode:"LTU",
     countryCode:"440"
  },
  {
     name:"Luxembourg",
     alphaCode:"LUX",
     countryCode:"442"
  },
  {
     name:"Macao",
     alphaCode:"MAC",
     countryCode:"446"
  },
  {
     name:"Madagascar",
     alphaCode:"MDG",
     countryCode:"450"
  },
  {
     name:"Malawi",
     alphaCode:"MWI",
     countryCode:"454"
  },
  {
     name:"Malaysia",
     alphaCode:"MYS",
     countryCode:"458"
  },
  {
     name:"Maldives",
     alphaCode:"MDV",
     countryCode:"462"
  },
  {
     name:"Mali",
     alphaCode:"MLI",
     countryCode:"466"
  },
  {
     name:"Malta",
     alphaCode:"MLT",
     countryCode:"470"
  },
  {
     name:"Marshall Islands",
     alphaCode:"MHL",
     countryCode:"584"
  },
  {
     name:"Martinique",
     alphaCode:"MTQ",
     countryCode:"474"
  },
  {
     name:"Mauritania",
     alphaCode:"MRT",
     countryCode:"478"
  },
  {
     name:"Mauritius",
     alphaCode:"MUS",
     countryCode:"480"
  },
  {
     name:"Mayotte",
     alphaCode:"MYT",
     countryCode:"175"
  },
  {
     name:"Mexico",
     alphaCode:"MEX",
     countryCode:"484"
  },
  {
     name:"Micronesia (Federated States of)",
     alphaCode:"FSM",
     countryCode:"583"
  },
  {
     name:"Moldova, Republic of",
     alphaCode:"MDA",
     countryCode:"498"
  },
  {
     name:"Monaco",
     alphaCode:"MCO",
     countryCode:"492"
  },
  {
     name:"Mongolia",
     alphaCode:"MNG",
     countryCode:"496"
  },
  {
     name:"Montenegro",
     alphaCode:"MNE",
     countryCode:"499"
  },
  {
     name:"Montserrat",
     alphaCode:"MSR",
     countryCode:"500"
  },
  {
     name:"Morocco",
     alphaCode:"MAR",
     countryCode:"504"
  },
  {
     name:"Mozambique",
     alphaCode:"MOZ",
     countryCode:"508"
  },
  {
     name:"Myanmar",
     alphaCode:"MMR",
     countryCode:"104"
  },
  {
     name:"Namibia",
     alphaCode:"NAM",
     countryCode:"516"
  },
  {
     name:"Nauru",
     alphaCode:"NRU",
     countryCode:"520"
  },
  {
     name:"Nepal",
     alphaCode:"NPL",
     countryCode:"524"
  },
  {
     name:"Netherlands",
     alphaCode:"NLD",
     countryCode:"528"
  },
  {
     name:"New Caledonia",
     alphaCode:"NCL",
     countryCode:"540"
  },
  {
     name:"New Zealand",
     alphaCode:"NZL",
     countryCode:"554"
  },
  {
     name:"Nicaragua",
     alphaCode:"NIC",
     countryCode:"558"
  },
  {
     name:"Niger",
     alphaCode:"NER",
     countryCode:"562"
  },
  {
     name:"Nigeria",
     alphaCode:"NGA",
     countryCode:"566"
  },
  {
     name:"Niue",
     alphaCode:"NIU",
     countryCode:"570"
  },
  {
     name:"Norfolk Island",
     alphaCode:"NFK",
     countryCode:"574"
  },
  {
     name:"North Macedonia",
     alphaCode:"MKD",
     countryCode:"807"
  },
  {
     name:"Northern Mariana Islands",
     alphaCode:"MNP",
     countryCode:"580"
  },
  {
     name:"Norway",
     alphaCode:"NOR",
     countryCode:"578"
  },
  {
     name:"Oman",
     alphaCode:"OMN",
     countryCode:"512"
  },
  {
     name:"Pakistan",
     alphaCode:"PAK",
     countryCode:"586"
  },
  {
     name:"Palau",
     alphaCode:"PLW",
     countryCode:"585"
  },
  {
     name:"Palestine, State of",
     alphaCode:"PSE",
     countryCode:"275"
  },
  {
     name:"Panama",
     alphaCode:"PAN",
     countryCode:"591"
  },
  {
     name:"Papua New Guinea",
     alphaCode:"PNG",
     countryCode:"598"
  },
  {
     name:"Paraguay",
     alphaCode:"PRY",
     countryCode:"600"
  },
  {
     name:"Peru",
     alphaCode:"PER",
     countryCode:"604"
  },
  {
     name:"Philippines",
     alphaCode:"PHL",
     countryCode:"608"
  },
  {
     name:"Pitcairn",
     alphaCode:"PCN",
     countryCode:"612"
  },
  {
     name:"Poland",
     alphaCode:"POL",
     countryCode:"616"
  },
  {
     name:"Portugal",
     alphaCode:"PRT",
     countryCode:"620"
  },
  {
     name:"Puerto Rico",
     alphaCode:"PRI",
     countryCode:"630"
  },
  {
     name:"Qatar",
     alphaCode:"QAT",
     countryCode:"634"
  },
  {
     name:"Réunion",
     alphaCode:"REU",
     countryCode:"638"
  },
  {
     name:"Romania",
     alphaCode:"ROU",
     countryCode:"642"
  },
  {
     name:"Russian Federation",
     alphaCode:"RUS",
     countryCode:"643"
  },
  {
     name:"Rwanda",
     alphaCode:"RWA",
     countryCode:"646"
  },
  {
     name:"Saint Barthélemy",
     alphaCode:"BLM",
     countryCode:"652"
  },
  {
     name:"Saint Helena, Ascension and Tristan da Cunha",
     alphaCode:"SHN",
     countryCode:"654"
  },
  {
     name:"Saint Kitts and Nevis",
     alphaCode:"KNA",
     countryCode:"659"
  },
  {
     name:"Saint Lucia",
     alphaCode:"LCA",
     countryCode:"662"
  },
  {
     name:"Saint Martin (French part)",
     alphaCode:"MAF",
     countryCode:"663"
  },
  {
     name:"Saint Pierre and Miquelon",
     alphaCode:"SPM",
     countryCode:"666"
  },
  {
     name:"Saint Vincent and the Grenadines",
     alphaCode:"VCT",
     countryCode:"670"
  },
  {
     name:"Samoa",
     alphaCode:"WSM",
     countryCode:"882"
  },
  {
     name:"San Marino",
     alphaCode:"SMR",
     countryCode:"674"
  },
  {
     name:"Sao Tome and Principe",
     alphaCode:"STP",
     countryCode:"678"
  },
  {
     name:"Saudi Arabia",
     alphaCode:"SAU",
     countryCode:"682"
  },
  {
     name:"Senegal",
     alphaCode:"SEN",
     countryCode:"686"
  },
  {
     name:"Serbia",
     alphaCode:"SRB",
     countryCode:"688"
  },
  {
     name:"Seychelles",
     alphaCode:"SYC",
     countryCode:"690"
  },
  {
     name:"Sierra Leone",
     alphaCode:"SLE",
     countryCode:"694"
  },
  {
     name:"Singapore",
     alphaCode:"SGP",
     countryCode:"702"
  },
  {
     name:"Sint Maarten (Dutch part)",
     alphaCode:"SXM",
     countryCode:"534"
  },
  {
     name:"Slovakia",
     alphaCode:"SVK",
     countryCode:"703"
  },
  {
     name:"Slovenia",
     alphaCode:"SVN",
     countryCode:"705"
  },
  {
     name:"Solomon Islands",
     alphaCode:"SLB",
     countryCode:"090"
  },
  {
     name:"Somalia",
     alphaCode:"SOM",
     countryCode:"706"
  },
  {
     name:"South Africa",
     alphaCode:"ZAF",
     countryCode:"710"
  },
  {
     name:"South Georgia and the South Sandwich Islands",
     alphaCode:"SGS",
     countryCode:"239"
  },
  {
     name:"South Sudan",
     alphaCode:"SSD",
     countryCode:"728"
  },
  {
     name:"Spain",
     alphaCode:"ESP",
     countryCode:"724"
  },
  {
     name:"Sri Lanka",
     alphaCode:"LKA",
     countryCode:"144"
  },
  {
     name:"Sudan",
     alphaCode:"SDN",
     countryCode:"729"
  },
  {
     name:"Suriname",
     alphaCode:"SUR",
     countryCode:"740"
  },
  {
     name:"Svalbard and Jan Mayen",
     alphaCode:"SJM",
     countryCode:"744"
  },
  {
     name:"Sweden",
     alphaCode:"SWE",
     countryCode:"752"
  },
  {
     name:"Switzerland",
     alphaCode:"CHE",
     countryCode:"756"
  },
  {
     name:"Syrian Arab Republic",
     alphaCode:"SYR",
     countryCode:"760"
  },
  {
     name:"Taiwan, Province of China",
     alphaCode:"TWN",
     countryCode:"158"
  },
  {
     name:"Tajikistan",
     alphaCode:"TJK",
     countryCode:"762"
  },
  {
     name:"Tanzania, United Republic of",
     alphaCode:"TZA",
     countryCode:"834"
  },
  {
     name:"Thailand",
     alphaCode:"THA",
     countryCode:"764"
  },
  {
     name:"Timor-Leste",
     alphaCode:"TLS",
     countryCode:"626"
  },
  {
     name:"Togo",
     alphaCode:"TGO",
     countryCode:"768"
  },
  {
     name:"Tokelau",
     alphaCode:"TKL",
     countryCode:"772"
  },
  {
     name:"Tonga",
     alphaCode:"TON",
     countryCode:"776"
  },
  {
     name:"Trinidad and Tobago",
     alphaCode:"TTO",
     countryCode:"780"
  },
  {
     name:"Tunisia",
     alphaCode:"TUN",
     countryCode:"788"
  },
  {
     name:"Turkey",
     alphaCode:"TUR",
     countryCode:"792"
  },
  {
     name:"Turkmenistan",
     alphaCode:"TKM",
     countryCode:"795"
  },
  {
     name:"Turks and Caicos Islands",
     alphaCode:"TCA",
     countryCode:"796"
  },
  {
     name:"Tuvalu",
     alphaCode:"TUV",
     countryCode:"798"
  },
  {
     name:"Uganda",
     alphaCode:"UGA",
     countryCode:"800"
  },
  {
     name:"Ukraine",
     alphaCode:"UKR",
     countryCode:"804"
  },
  {
     name:"United Arab Emirates",
     alphaCode:"ARE",
     countryCode:"784"
  },
  {
     name:"United Kingdom of Great Britain and Northern Ireland",
     alphaCode:"GBR",
     countryCode:"826"
  },
  {
     name:"United States of America",
     alphaCode:"USA",
     countryCode:"840"
  },
  {
     name:"United States Minor Outlying Islands",
     alphaCode:"UMI",
     countryCode:"581"
  },
  {
     name:"Uruguay",
     alphaCode:"URY",
     countryCode:"858"
  },
  {
     name:"Uzbekistan",
     alphaCode:"UZB",
     countryCode:"860"
  },
  {
     name:"Vanuatu",
     alphaCode:"VUT",
     countryCode:"548"
  },
  {
     name:"Venezuela (Bolivarian Republic of)",
     alphaCode:"VEN",
     countryCode:"862"
  },
  {
     name:"Viet Nam",
     alphaCode:"VNM",
     countryCode:"704"
  },
  {
     name:"Virgin Islands (British)",
     alphaCode:"VGB",
     countryCode:"092"
  },
  {
     name:"Virgin Islands (U.S.)",
     alphaCode:"VIR",
     countryCode:"850"
  },
  {
     name:"Wallis and Futuna",
     alphaCode:"WLF",
     countryCode:"876"
  },
  {
     name:"Western Sahara",
     alphaCode:"ESH",
     countryCode:"732"
  },
  {
     name:"Yemen",
     alphaCode:"YEM",
     countryCode:"887"
  },
  {
     name:"Zambia",
     alphaCode:"ZMB",
     countryCode:"894"
  },
  {
     name:"Zimbabwe",
     alphaCode:"ZWE",
     countryCode:"716"
  }
]
